import type { IntakeCase, CallLog, ClioRecord, CaseEvaluation, DocusealRetainer } from "./supabase";

// Helper to generate dates relative to now
const daysAgo = (days: number): string => {
  const date = new Date();
  date.setDate(date.getDate() - days);
  return date.toISOString();
};

export const MOCK_INTAKE_CASES: IntakeCase[] = [
  {
    id: "mock-1",
    call_id: "call-1",
    call_type: "Inbound",
    call_status: "Completed",
    call_started_at: daysAgo(0.1),
    call_ended_at: daysAgo(0.095),
    call_duration_seconds: "432",
    ended_reason: "Customer Hung Up",
    client_name: "Sarah Jenkins",
    phone: "+15125550192",
    customer_number: "+15125550192",
    transcript: "AI: Thank you for calling Harrington Law. This is Alex. I'm sorry you're dealing with an accident. I can collect the key details now. To start, what is your name?\nUser: Hi, my name is Sarah Jenkins. I was rear-ended on my way home from work yesterday.\nAI: I'm sorry to hear that, Sarah. Let me get some details. Were you injured?\nUser: Yes, my neck and back are extremely sore. I went to the ER last night and they diagnosed me with whiplash and gave me a neck brace.\nAI: That sounds painful. What date and time did the accident happen?\nUser: It happened yesterday afternoon around 5:30 PM. I was stopped at a red light on 5th Street and a pickup truck slammed into the back of my Honda Civic.\nAI: Did the police come to the scene?\nUser: Yes, they did. A police report was filed. The other driver was cited for distracted driving; he was texting.\nAI: Do you have insurance and do you know if the other driver has insurance?\nUser: Yes, I have Geico, and the other driver has State Farm. I have his policy info here.\nAI: Excellent. We will help you navigate this. I'll pass this information to our attorneys immediately.",
    recording_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3", // Demo audio file
    stereo_recording_url: null,
    log_url: null,
    accident_date: daysAgo(1).split("T")[0],
    incident_summary: "Rear-ended by a pickup truck while stopped at a red light on 5th Street. Other driver was texting and cited at the scene. Whiplash and back pain diagnosed at the ER.",
    police_report: "Yes - Police report filed, other driver cited.",
    medical_documentation: "Yes - ER visit, neck brace, diagnosed whiplash.",
    insurance_status: "Yes - Insured. Client has Geico, other driver has State Farm.",
    at_fault: "No - Other driver rear-ended client stopped at red light.",
    case_evaluation_memo: "### CASE EVALUATION MEMO\n\n**Client Name**: Sarah Jenkins\n**Accident Date**: Yesterday\n**Liability**: Clear liability. Rear-end collision while client was stationary at a red light. Defendant cited for distracted driving.\n**Injuries**: ER visit, whiplash, neck brace, lower back pain.\n**Coverage**: Geico (Client) and State Farm (Defendant). High probability of coverage.\n**Recommendation**: Accept case immediately. Send retainer.",
    liability_assessment: "Clear liability on the other driver.",
    liability_reason: "Rear-end collision. Defendant cited for texting/distracted driving.",
    viability_score: "95",
    recommended_action: "Accept Case - Send Retainer",
    extraction_status: "Completed",
    clio_contact_id: "clio-c-1",
    clio_matter_id: "clio-m-1",
    clio_matter_status: "Open",
    clio_note_id: "clio-n-1",
    sms_message: "Hi Sarah, Harrington Law is reviewing your accident case. We have sent a retainer agreement to your email.",
    sms_status: "Sent",
    sms_sent_at: daysAgo(0.09),
    docuseal_submission_id: "sub-1",
    docuseal_status: "Completed",
    docuseal_document_url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    docuseal_audit_log_url: null,
    retainer_sent_at: daysAgo(0.09),
    retainer_signed_at: daysAgo(0.08),
    slack_status: "Sent",
    slack_message: "🚨 NEW SIGNED CASE: Sarah Jenkins. MVA - Rear-ended at Red Light. Viability: 95/100. Retainer signed!",
    slack_sent_at: daysAgo(0.08),
    created_at: daysAgo(0.1),
    updated_at: daysAgo(0.08),
    raw_payload: null
  },
  {
    id: "mock-2",
    call_id: "call-2",
    call_type: "Inbound",
    call_status: "Completed",
    call_started_at: daysAgo(1.2),
    call_ended_at: daysAgo(1.19),
    call_duration_seconds: "310",
    ended_reason: "Completed",
    client_name: "Marcus Aurelius",
    phone: "+15125550882",
    customer_number: "+15125550882",
    transcript: "AI: Hello. This is Alex with Harrington Law. How can I help you?\nUser: Yes, I fell down at a grocery store earlier today. There was a huge puddle of water in the aisle with no warning sign.\nAI: Oh, I'm very sorry. Did you get hurt?\nUser: Yes, I landed hard on my left knee. It is swollen and I can barely walk. I had to leave work and I'm currently waiting at the urgent care clinic.\nAI: I hope your knee is okay, Marcus. Did the store management write up a report?\nUser: Yes, the manager took down my name, and I took photos of the water on the floor and the lack of warning signs.\nAI: Photos are great. Did they say where the water came from?\nUser: The manager said a refrigerator case had been leaking all morning. They knew about it but hadn't cleaned it up.",
    recording_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    stereo_recording_url: null,
    log_url: null,
    accident_date: daysAgo(1.2).split("T")[0],
    incident_summary: "Slipped and fell on a large puddle of water leaking from a refrigerator case at HEB Grocery. Management was aware of the leak. No wet floor warning signs present. Client has a severely swollen left knee and is at urgent care.",
    police_report: "No - Store incident report filed by manager.",
    medical_documentation: "Yes - Urgent care clinic visit in progress.",
    insurance_status: "Yes - HEB is self-insured/commercial liability policy.",
    at_fault: "No - Store knew about refrigerator leak and failed to place warning signs.",
    case_evaluation_memo: "### CASE EVALUATION MEMO\n\n**Client Name**: Marcus Aurelius\n**Accident Date**: Today\n**Liability**: Strong premises liability. Store manager admitted knowledge of refrigerator leak prior to the fall. No signs posted.\n**Injuries**: Left knee injury (severe swelling, possible meniscus tear/sprain).\n**Recommendation**: Retain case. Schedule follow-up after urgent care diagnosis.",
    liability_assessment: "Strong Premises Liability",
    liability_reason: "Notice of leak existed; failure to warn or remediate dangerous condition.",
    viability_score: "85",
    recommended_action: "Accept Case - Send Retainer",
    extraction_status: "Completed",
    clio_contact_id: "clio-c-2",
    clio_matter_id: "clio-m-2",
    clio_matter_status: "Open",
    clio_note_id: "clio-n-2",
    sms_message: "Hello Marcus, we are reviewing your slip and fall incident at HEB. Retainer agreement has been sent to your email.",
    sms_status: "Sent",
    sms_sent_at: daysAgo(1.15),
    docuseal_submission_id: "sub-2",
    docuseal_status: "Sent",
    docuseal_document_url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    docuseal_audit_log_url: null,
    retainer_sent_at: daysAgo(1.15),
    retainer_signed_at: null,
    slack_status: "Sent",
    slack_message: "⚠️ NEW CASE: Marcus Aurelius. Premises Liability - Slip & Fall at HEB. Viability: 85/100. Retainer sent.",
    slack_sent_at: daysAgo(1.15),
    created_at: daysAgo(1.2),
    updated_at: daysAgo(1.15),
    raw_payload: null
  },
  {
    id: "mock-3",
    call_id: "call-3",
    call_type: "Inbound",
    call_status: "Completed",
    call_started_at: daysAgo(2.5),
    call_ended_at: daysAgo(2.48),
    call_duration_seconds: "215",
    ended_reason: "Completed",
    client_name: "Elena Rostova",
    phone: "+15125550212",
    customer_number: "+15125550212",
    transcript: "AI: Thank you for calling Harrington Law. This is Alex. How can I assist you?\nUser: Hi, I was in a car crash about 3 months ago. I was speeding a bit and hit a car that was making a left turn in front of me.\nAI: I see. Were you injured?\nUser: No, I wasn't really hurt, just some soreness that went away in a few days. My car had some bumper damage but it's already fixed.\nAI: Okay, did the police come?\nUser: Yeah, the police report said I was 50% at fault for speeding, and the other guy was 50% for failing to yield.\nAI: Thank you. Let me evaluate this case.",
    recording_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    stereo_recording_url: null,
    log_url: null,
    accident_date: daysAgo(90).split("T")[0],
    incident_summary: "Car crash 3 months ago. Left turn collision, but client admits speeding. Police report split fault 50/50. No physical injuries, bumper damage has already been repaired.",
    police_report: "Yes - 50/50 fault allocation.",
    medical_documentation: "No - Soreness resolved within days, no treatment sought.",
    insurance_status: "Yes - Property damage already handled by insurance.",
    at_fault: "Partial - Speeding, 50% comparative negligence.",
    case_evaluation_memo: "### CASE EVALUATION MEMO\n\n**Client Name**: Elena Rostova\n**Accident Date**: 90 days ago\n**Liability**: Contested. 50% comparative fault for speeding.\n**Injuries**: None. Soft tissue soreness fully resolved. No medical records.\n**Damages**: None. Property damage already resolved.\n**Recommendation**: Decline case. No bodily injury damages and property damage settled.",
    liability_assessment: "Low / Split Liability",
    liability_reason: "Comparative negligence and lack of damages.",
    viability_score: "35",
    recommended_action: "Decline Case",
    extraction_status: "Completed",
    clio_contact_id: null,
    clio_matter_id: null,
    clio_matter_status: null,
    clio_note_id: null,
    sms_message: "Hello Elena, thank you for contacting Harrington Law. After review, we are unable to take your case due to the lack of injury damages and fault distribution. We wish you the best.",
    sms_status: "Sent",
    sms_sent_at: daysAgo(2.45),
    docuseal_submission_id: null,
    docuseal_status: null,
    docuseal_document_url: null,
    docuseal_audit_log_url: null,
    retainer_sent_at: null,
    retainer_signed_at: null,
    slack_status: "Sent",
    slack_message: "ℹ️ CASE DECLINED: Elena Rostova. MVA - 50/50 liability, no injuries. Viability: 35/100. Rejection SMS sent.",
    slack_sent_at: daysAgo(2.45),
    created_at: daysAgo(2.5),
    updated_at: daysAgo(2.45),
    raw_payload: null
  },
  {
    id: "mock-4",
    call_id: "call-4",
    call_type: "Inbound",
    call_status: "Completed",
    call_started_at: daysAgo(4.1),
    call_ended_at: daysAgo(4.09),
    call_duration_seconds: "389",
    ended_reason: "Completed",
    client_name: "Daniel Craig",
    phone: "+15125559381",
    customer_number: "+15125559381",
    transcript: "AI: Thank you for calling Harrington Law. This is Alex. Tell me what happened.\nUser: Yes, I was riding my bicycle in the bike lane on Congress Ave, and a delivery van suddenly turned right across the lane, cutting me off. I slammed into the side of the van.\nAI: That sounds terrifying, Daniel. Are you injured?\nUser: Yes, I have a fractured collarbone and severe road rash. I spent two days in the hospital and had surgery to insert a plate in my shoulder.\nAI: I'm so sorry, that is a major injury. Was the delivery driver working at the time?\nUser: Yes, it was an Amazon delivery van. The police ticketed the driver for failure to yield. I have the crash ID number.",
    recording_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
    stereo_recording_url: null,
    log_url: null,
    accident_date: daysAgo(6).split("T")[0],
    incident_summary: "Bicyclist struck by Amazon delivery van making an illegal right turn across the bicycle lane on Congress Ave. Driver cited for failure to yield. Client suffered fractured collarbone requiring surgery and plates, and severe road rash.",
    police_report: "Yes - Amazon driver cited for failure to yield.",
    medical_documentation: "Yes - Hospitalization, orthopedic surgery (shoulder plate), collarbone fracture.",
    insurance_status: "Yes - Amazon Commercial Liability Policy (high coverage).",
    at_fault: "No - Delivery van cut off bicyclist in designated bike lane.",
    case_evaluation_memo: "### CASE EVALUATION MEMO\n\n**Client Name**: Daniel Craig\n**Accident Date**: 6 days ago\n**Liability**: Clear liability. Commercial vehicle cut off bicyclist in dedicated bike lane. Citation issued.\n**Injuries**: Fractured clavicle requiring open reduction internal fixation (ORIF surgery), severe abrasions.\n**Damages**: Substantial medical bills, surgical hardware, permanent scarring potential, lost wages.\n**Recommendation**: Accept case immediately, high value case, commercial policy limits.\n**Action**: Clio Matter created and Retainer signed.",
    liability_assessment: "Clear Liability - Commercial Defendant",
    liability_reason: "Commercial vehicle cut off bicycle in designated lane. Citation issued.",
    viability_score: "98",
    recommended_action: "Accept Case - Send Retainer",
    extraction_status: "Completed",
    clio_contact_id: "clio-c-4",
    clio_matter_id: "clio-m-4",
    clio_matter_status: "Open",
    clio_note_id: "clio-n-4",
    sms_message: "Hi Daniel, Harrington Law has received your signed retainer. We have opened your file (Matter ID: clio-m-4) and will be requesting the police crash report today.",
    sms_status: "Sent",
    sms_sent_at: daysAgo(3.9),
    docuseal_submission_id: "sub-4",
    docuseal_status: "Completed",
    docuseal_document_url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    docuseal_audit_log_url: null,
    retainer_sent_at: daysAgo(4.0),
    retainer_signed_at: daysAgo(3.95),
    slack_status: "Sent",
    slack_message: "🔥 HUGE CASE ALERT: Daniel Craig. Bicycle vs. Amazon Van. Fractured collarbone + surgery. Viability: 98/100. Clio Matter opened and Retainer signed!",
    slack_sent_at: daysAgo(3.9),
    created_at: daysAgo(4.1),
    updated_at: daysAgo(3.9),
    raw_payload: null
  },
  {
    id: "mock-5",
    call_id: "call-5",
    call_type: "Inbound",
    call_status: "Completed",
    call_started_at: daysAgo(5.8),
    call_ended_at: daysAgo(5.79),
    call_duration_seconds: "280",
    ended_reason: "Completed",
    client_name: "Amanda Seyfried",
    phone: "+15125556272",
    customer_number: "+15125556272",
    transcript: "AI: Thank you for calling Harrington Law. This is Alex. How can I help?\nUser: Yes, I went to a local beauty salon last week for a hair bleaching treatment, and the stylist left the chemicals on too long. My scalp got chemical burns, and chunks of my hair have fallen out.\nAI: That is terrible, Amanda. Have you seen a doctor?\nUser: Yes, I went to a dermatologist. She confirmed I have second-degree chemical burns on my scalp, and she's not sure if the hair will ever grow back in those spots.\nAI: That is devastating. Did the salon apologize or offer anything?\nUser: They refunded my money, but they won't give me their insurance info. I took photos of my scalp and the hair that fell out.",
    recording_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
    stereo_recording_url: null,
    log_url: null,
    accident_date: daysAgo(10).split("T")[0],
    incident_summary: "Stylist at a hair salon left bleaching chemicals on client's scalp for an excessive duration. Client suffered second-degree chemical burns on her scalp, leading to patch alopecia (permanent hair loss). Dermatologist confirmed diagnosis.",
    police_report: "No - Not a police matter.",
    medical_documentation: "Yes - Dermatologist report, second-degree chemical burns, hair loss prognosis.",
    insurance_status: "Pending - Salon refunding service but withholding liability insurance details.",
    at_fault: "No - Stylist left chemicals on too long, violating standard training/protocol.",
    case_evaluation_memo: "### CASE EVALUATION MEMO\n\n**Client Name**: Amanda Seyfried\n**Accident Date**: 10 days ago\n**Liability**: Strong liability. Chemical application time exceeded salon protocols. Photos show clear burns.\n**Injuries**: Second-degree chemical scalp burns, permanent localized alopecia, significant emotional distress.\n**Recommendation**: Accept case. Send spoliation letter to salon to preserve video, employee records, and chemical logs.",
    liability_assessment: "Strong Professional Liability / Negligence",
    liability_reason: "Negligent chemical application leading to bodily injury.",
    viability_score: "80",
    recommended_action: "Accept Case - Send Retainer",
    extraction_status: "Completed",
    clio_contact_id: "clio-c-5",
    clio_matter_id: null,
    clio_matter_status: null,
    clio_note_id: null,
    sms_message: "Hi Amanda, Harrington Law is ready to assist with your scalp injury case. We've created your contact record and sent a retainer to your email.",
    sms_status: "Sent",
    sms_sent_at: daysAgo(5.7),
    docuseal_submission_id: "sub-5",
    docuseal_status: "Sent",
    docuseal_document_url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    docuseal_audit_log_url: null,
    retainer_sent_at: daysAgo(5.7),
    retainer_signed_at: null,
    slack_status: "Sent",
    slack_message: "💇‍♀️ NEW CASE: Amanda Seyfried. Salon Negligence - Scalp chemical burns. Viability: 80/100. Retainer sent.",
    slack_sent_at: daysAgo(5.7),
    created_at: daysAgo(5.8),
    updated_at: daysAgo(5.7),
    raw_payload: null
  },
  {
    id: "mock-6",
    call_id: "call-6",
    call_type: "Inbound",
    call_status: "Completed",
    call_started_at: daysAgo(7.3),
    call_ended_at: daysAgo(7.29),
    call_duration_seconds: "182",
    ended_reason: "Completed",
    client_name: "Robert Downey",
    phone: "+15125553940",
    customer_number: "+15125553940",
    transcript: "AI: Hello. This is Alex with Harrington Law. How can I help you?\nUser: Yes, I slipped on some ice on the public sidewalk outside my apartment building. I twisted my ankle.\nAI: I'm sorry to hear that. Did you go to the hospital?\nUser: No, I just went home, put some ice on it, and it feels okay now. I was just wondering if I could sue the city or the apartment for not salting the sidewalk.\nAI: Were there any witnesses or reports filed?\nUser: No, just me. And I didn't see a doctor because it's mostly fine now, just a tiny bit stiff.\nAI: Thank you. Let me analyze this.",
    recording_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
    stereo_recording_url: null,
    log_url: null,
    accident_date: daysAgo(8).split("T")[0],
    incident_summary: "Slipped on sidewalk ice outside apartment building. Sidewalk was public. Twisted ankle but did not seek medical treatment. Ankle is currently fine.",
    police_report: "No - No report.",
    medical_documentation: "No - No doctor visit, self-treated with ice, recovered.",
    insurance_status: "No - Sidewalk is public property; municipal liability is highly restricted.",
    at_fault: "Yes/No - Slipping on natural accumulation of ice is generally not actionable in this jurisdiction.",
    case_evaluation_memo: "### CASE EVALUATION MEMO\n\n**Client Name**: Robert Downey\n**Accident Date**: 8 days ago\n**Liability**: Very low. Natural accumulation of ice is standard risk. Public sidewalk places liability on city which has sovereign immunity defenses.\n**Injuries**: De minimis. Twisted ankle, recovered, no medical bills.\n**Recommendation**: Decline case. No damages, tough liability.",
    liability_assessment: "De Minimis Liability & Damages",
    liability_reason: "No medical damages, municipal natural accumulation rules.",
    viability_score: "15",
    recommended_action: "Decline Case",
    extraction_status: "Completed",
    clio_contact_id: null,
    clio_matter_id: null,
    clio_matter_status: null,
    clio_note_id: null,
    sms_message: "Hi Robert, thank you for contacting Harrington Law. Based on the lack of medical treatment and injuries, we cannot represent you in this slip on public ice. Good luck.",
    sms_status: "Sent",
    sms_sent_at: daysAgo(7.2),
    docuseal_submission_id: null,
    docuseal_status: null,
    docuseal_document_url: null,
    docuseal_audit_log_url: null,
    retainer_sent_at: null,
    retainer_signed_at: null,
    slack_status: "Sent",
    slack_message: "❌ CASE DECLINED: Robert Downey. Slip on ice - Twisted ankle, no medicals. Viability: 15/100. SMS sent.",
    slack_sent_at: daysAgo(7.2),
    created_at: daysAgo(7.3),
    updated_at: daysAgo(7.2),
    raw_payload: null
  }
];

export const MOCK_CALL_LOGS: CallLog[] = [
  {
    id: "call-1",
    call_id: "call-1",
    assistant_id: "asst-alex-pi",
    assistant_name: "Alex - PI Intake",
    phone_number_id: "phone-in-1",
    inbound_number: "+18005550100",
    customer_number: "+15125550192",
    started_at: daysAgo(0.1),
    ended_at: daysAgo(0.095),
    duration_seconds: "432",
    duration_minutes: "7.2",
    ended_reason: "Customer Hung Up",
    transcript: "AI: Thank you for calling... (see case transcript)",
    summary: "Sarah Jenkins called regarding a rear-end MVA yesterday. Severe whiplash, went to ER. Geico/State Farm coverage. Police report filed.",
    recording_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    stereo_recording_url: null,
    pcap_url: null,
    log_url: "https://vapi.ai/logs/call-1",
    cost: "0.85",
    stt_cost: "0.08",
    llm_cost: "0.22",
    tts_cost: "0.35",
    vapi_cost: "0.20",
    total_cost: "0.85",
    model_name: "gpt-4o",
    voice_provider: "Cartesia",
    voice_id: "sheriff-male",
    transcriber_provider: "Deepgram",
    transcriber_model: "nova-2",
    raw_payload: null,
    created_at: daysAgo(0.1)
  },
  {
    id: "call-2",
    call_id: "call-2",
    assistant_id: "asst-alex-pi",
    assistant_name: "Alex - PI Intake",
    phone_number_id: "phone-in-1",
    inbound_number: "+18005550100",
    customer_number: "+15125550882",
    started_at: daysAgo(1.2),
    ended_at: daysAgo(1.19),
    duration_seconds: "310",
    duration_minutes: "5.17",
    ended_reason: "Completed",
    transcript: "AI: Hello. This is Alex... (see case transcript)",
    summary: "Marcus Aurelius slipped on water leaking from a grocery store refrigerator. Left knee swollen, at urgent care. Management filed incident report. Photos taken.",
    recording_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    stereo_recording_url: null,
    pcap_url: null,
    log_url: "https://vapi.ai/logs/call-2",
    cost: "0.62",
    stt_cost: "0.06",
    llm_cost: "0.16",
    tts_cost: "0.25",
    vapi_cost: "0.15",
    total_cost: "0.62",
    model_name: "gpt-4o",
    voice_provider: "Cartesia",
    voice_id: "sheriff-male",
    transcriber_provider: "Deepgram",
    transcriber_model: "nova-2",
    raw_payload: null,
    created_at: daysAgo(1.2)
  },
  {
    id: "call-3",
    call_id: "call-3",
    assistant_id: "asst-alex-pi",
    assistant_name: "Alex - PI Intake",
    phone_number_id: "phone-in-1",
    inbound_number: "+18005550100",
    customer_number: "+15125550212",
    started_at: daysAgo(2.5),
    ended_at: daysAgo(2.48),
    duration_seconds: "215",
    duration_minutes: "3.58",
    ended_reason: "Completed",
    transcript: "AI: Thank you... (see case transcript)",
    summary: "Elena Rostova crashed 3 months ago. Left turn collision, admits speeding. No injuries, property damage already resolved.",
    recording_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    stereo_recording_url: null,
    pcap_url: null,
    log_url: "https://vapi.ai/logs/call-3",
    cost: "0.45",
    stt_cost: "0.04",
    llm_cost: "0.11",
    tts_cost: "0.20",
    vapi_cost: "0.10",
    total_cost: "0.45",
    model_name: "gpt-4o-mini",
    voice_provider: "Elevenlabs",
    voice_id: "rachel",
    transcriber_provider: "Deepgram",
    transcriber_model: "nova-2",
    raw_payload: null,
    created_at: daysAgo(2.5)
  },
  {
    id: "call-4",
    call_id: "call-4",
    assistant_id: "asst-alex-pi",
    assistant_name: "Alex - PI Intake",
    phone_number_id: "phone-in-1",
    inbound_number: "+18005550100",
    customer_number: "+15125559381",
    started_at: daysAgo(4.1),
    ended_at: daysAgo(4.09),
    duration_seconds: "389",
    duration_minutes: "6.48",
    ended_reason: "Completed",
    transcript: "AI: Thank you... (see case transcript)",
    summary: "Bicyclist Daniel Craig cut off by Amazon delivery van. Fractured collarbone, surgery. Clear liability, police report filed, Amazon cited.",
    recording_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
    stereo_recording_url: null,
    pcap_url: null,
    log_url: "https://vapi.ai/logs/call-4",
    cost: "0.78",
    stt_cost: "0.07",
    llm_cost: "0.20",
    tts_cost: "0.33",
    vapi_cost: "0.18",
    total_cost: "0.78",
    model_name: "gpt-4o",
    voice_provider: "Cartesia",
    voice_id: "sheriff-male",
    transcriber_provider: "Deepgram",
    transcriber_model: "nova-2",
    raw_payload: null,
    created_at: daysAgo(4.1)
  },
  {
    id: "call-5",
    call_id: "call-5",
    assistant_id: "asst-alex-pi",
    assistant_name: "Alex - PI Intake",
    phone_number_id: "phone-in-1",
    inbound_number: "+18005550100",
    customer_number: "+15125556272",
    started_at: daysAgo(5.8),
    ended_at: daysAgo(5.79),
    duration_seconds: "280",
    duration_minutes: "4.67",
    ended_reason: "Completed",
    transcript: "AI: Thank you... (see case transcript)",
    summary: "Amanda Seyfried suffered scalp chemical burns and hair loss due to beauty salon bleach treatment error. Dermatologist diagnosed 2nd degree burns.",
    recording_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
    stereo_recording_url: null,
    pcap_url: null,
    log_url: "https://vapi.ai/logs/call-5",
    cost: "0.58",
    stt_cost: "0.05",
    llm_cost: "0.15",
    tts_cost: "0.24",
    vapi_cost: "0.14",
    total_cost: "0.58",
    model_name: "gpt-4o-mini",
    voice_provider: "Elevenlabs",
    voice_id: "rachel",
    transcriber_provider: "Deepgram",
    transcriber_model: "nova-2",
    raw_payload: null,
    created_at: daysAgo(5.8)
  },
  {
    id: "call-6",
    call_id: "call-6",
    assistant_id: "asst-alex-pi",
    assistant_name: "Alex - PI Intake",
    phone_number_id: "phone-in-1",
    inbound_number: "+18005550100",
    customer_number: "+15125553940",
    started_at: daysAgo(7.3),
    ended_at: daysAgo(7.29),
    duration_seconds: "182",
    duration_minutes: "3.03",
    ended_reason: "Completed",
    transcript: "AI: Hello... (see case transcript)",
    summary: "Robert Downey slipped on ice on public sidewalk outside apartment. Twisted ankle, no medical treatment, ankle is fine now.",
    recording_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
    stereo_recording_url: null,
    pcap_url: null,
    log_url: "https://vapi.ai/logs/call-6",
    cost: "0.38",
    stt_cost: "0.03",
    llm_cost: "0.09",
    tts_cost: "0.16",
    vapi_cost: "0.10",
    total_cost: "0.38",
    model_name: "gpt-4o-mini",
    voice_provider: "Elevenlabs",
    voice_id: "rachel",
    transcriber_provider: "Deepgram",
    transcriber_model: "nova-2",
    raw_payload: null,
    created_at: daysAgo(7.3)
  }
];

export const MOCK_CLIO_RECORDS: ClioRecord[] = [
  {
    id: "clio-1",
    call_id: "call-1",
    client_name: "Sarah Jenkins",
    phone: "+15125550192",
    clio_contact_id: "24609395",
    clio_contact_response: '{"id":24609395,"first_name":"Sarah","last_name":"Jenkins","type":"Person"}',
    clio_matter_id: "10928374",
    clio_matter_status: "Open",
    clio_matter_description: "MVA - Rear-ended by pickup truck on 5th Street stopped at red light",
    practice_area: "Motor Vehicle Accident",
    clio_matter_response: '{"id":10928374,"display_number":"00124-2026","status":"Open","description":"Rear-ended on 5th St"}',
    clio_note_id: "note-1",
    clio_note_subject: "AI Intake Summary - Whiplash ER Visit",
    clio_note_detail: "Sarah Jenkins was rear-ended. Neck brace, whiplash, police report filed. Geico vs State Farm.",
    clio_note_response: '{"id":"note-1","subject":"AI Intake Summary"}',
    created_at: daysAgo(0.08),
    updated_at: daysAgo(0.08)
  },
  {
    id: "clio-2",
    call_id: "call-2",
    client_name: "Marcus Aurelius",
    phone: "+15125550882",
    clio_contact_id: "24609396",
    clio_contact_response: '{"id":24609396,"first_name":"Marcus","last_name":"Aurelius","type":"Person"}',
    clio_matter_id: "10928375",
    clio_matter_status: "Pending Approval",
    clio_matter_description: "Slip & Fall - HEB grocery refrigerator puddle leak",
    practice_area: "Premises Liability",
    clio_matter_response: '{"id":10928375,"status":"Pending Approval"}',
    clio_note_id: "note-2",
    clio_note_subject: "AI Slip & Fall Intake Summary",
    clio_note_detail: "Slipped on water leaking from cooler. Swollen left knee, urgent care. Photos taken, manager reported.",
    clio_note_response: '{"id":"note-2","subject":"AI Intake Summary"}',
    created_at: daysAgo(1.15),
    updated_at: daysAgo(1.15)
  },
  {
    id: "clio-4",
    call_id: "call-4",
    client_name: "Daniel Craig",
    phone: "+15125559381",
    clio_contact_id: "24609398",
    clio_contact_response: '{"id":24609398,"first_name":"Daniel","last_name":"Craig","type":"Person"}',
    clio_matter_id: "10928378",
    clio_matter_status: "Open",
    clio_matter_description: "Bicycle vs Amazon Delivery Van on Congress Ave",
    practice_area: "Bicycle Accident",
    clio_matter_response: '{"id":10928378,"display_number":"00121-2026","status":"Open"}',
    clio_note_id: "note-4",
    clio_note_subject: "AI Intake - Amazon Van Clavicle Fracture",
    clio_note_detail: "Daniel Craig hit by Amazon van cutting off bike lane. Clavicle surgery with plates. High value target.",
    clio_note_response: '{"id":"note-4"}',
    created_at: daysAgo(3.9),
    updated_at: daysAgo(3.9)
  },
  {
    id: "clio-5",
    call_id: "call-5",
    client_name: "Amanda Seyfried",
    phone: "+15125556272",
    clio_contact_id: "24609399",
    clio_contact_response: '{"id":24609399,"first_name":"Amanda","last_name":"Seyfried","type":"Person"}',
    clio_matter_id: null,
    clio_matter_status: null,
    clio_matter_description: null,
    practice_area: "Professional Negligence",
    clio_matter_response: null,
    clio_note_id: null,
    clio_note_subject: null,
    clio_note_detail: null,
    clio_note_response: null,
    created_at: daysAgo(5.7),
    updated_at: daysAgo(5.7)
  }
];

export const MOCK_CASE_EVALUATIONS: CaseEvaluation[] = [
  {
    id: "eval-1",
    call_id: "call-1",
    client_name: "Sarah Jenkins",
    accident_date: daysAgo(1).split("T")[0],
    incident_summary: "Rear-ended by a pickup truck while stopped at a red light on 5th Street. Other driver was texting and cited at the scene. Whiplash and back pain diagnosed at the ER.",
    liability_assessment: "Clear Liability",
    liability_reason: "Rear-end collision. Defendant cited for texting/distracted driving.",
    medical_documentation: "Yes - ER visit, neck brace, diagnosed whiplash.",
    police_report_status: "Filed",
    police_report: "Yes - Police report filed, other driver cited.",
    insurance_status: "Yes - Insured. Client has Geico, other driver has State Farm.",
    viability_score: "95",
    recommended_action: "Accept Case - Send Retainer",
    case_evaluation_memo: "### CASE EVALUATION MEMO\n\n**Client Name**: Sarah Jenkins\n**Accident Date**: Yesterday\n**Liability**: Clear liability. Rear-end collision while client was stationary at a red light. Defendant cited for distracted driving.\n**Injuries**: ER visit, whiplash, neck brace, lower back pain.\n**Coverage**: Geico (Client) and State Farm (Defendant). High probability of coverage.\n**Recommendation**: Accept case immediately. Send retainer.",
    extraction_status: "Completed",
    created_at: daysAgo(0.09),
    raw_payload: null
  },
  {
    id: "eval-2",
    call_id: "call-2",
    client_name: "Marcus Aurelius",
    accident_date: daysAgo(1.2).split("T")[0],
    incident_summary: "Slipped and fell on a large puddle of water leaking from a refrigerator case at HEB Grocery. Management was aware of the leak. No wet floor warning signs present. Client has a severely swollen left knee and is at urgent care.",
    liability_assessment: "Strong Premises Liability",
    liability_reason: "Notice of leak existed; failure to warn or remediate dangerous condition.",
    medical_documentation: "Yes - Urgent care clinic visit in progress.",
    police_report_status: "Not Applicable",
    police_report: "No - Store incident report filed by manager.",
    insurance_status: "Yes - HEB is self-insured/commercial liability policy.",
    viability_score: "85",
    recommended_action: "Accept Case - Send Retainer",
    case_evaluation_memo: "### CASE EVALUATION MEMO\n\n**Client Name**: Marcus Aurelius\n**Accident Date**: Today\n**Liability**: Strong premises liability. Store manager admitted knowledge of refrigerator leak prior to the fall. No signs posted.\n**Injuries**: Left knee injury (severe swelling, possible meniscus tear/sprain).\n**Recommendation**: Retain case. Schedule follow-up after urgent care diagnosis.",
    extraction_status: "Completed",
    created_at: daysAgo(1.18),
    raw_payload: null
  },
  {
    id: "eval-3",
    call_id: "call-3",
    client_name: "Elena Rostova",
    accident_date: daysAgo(90).split("T")[0],
    incident_summary: "Car crash 3 months ago. Left turn collision, but client admits speeding. Police report split fault 50/50. No physical injuries, bumper damage has already been repaired.",
    liability_assessment: "Low / Split Liability",
    liability_reason: "Comparative negligence and lack of damages.",
    medical_documentation: "No - Soreness resolved within days, no treatment sought.",
    police_report_status: "Filed",
    police_report: "Yes - 50/50 fault allocation.",
    insurance_status: "Yes - Property damage already handled by insurance.",
    viability_score: "35",
    recommended_action: "Decline Case",
    case_evaluation_memo: "### CASE EVALUATION MEMO\n\n**Client Name**: Elena Rostova\n**Accident Date**: 90 days ago\n**Liability**: Contested. 50% comparative fault for speeding.\n**Injuries**: None. Soft tissue soreness fully resolved. No medical records.\n**Damages**: None. Property damage already resolved.\n**Recommendation**: Decline case. No bodily injury damages and property damage settled.",
    extraction_status: "Completed",
    created_at: daysAgo(2.47),
    raw_payload: null
  },
  {
    id: "eval-4",
    call_id: "call-4",
    client_name: "Daniel Craig",
    accident_date: daysAgo(6).split("T")[0],
    incident_summary: "Bicyclist struck by Amazon delivery van making an illegal right turn across the bicycle lane on Congress Ave. Driver cited for failure to yield. Client suffered fractured collarbone requiring surgery and plates, and severe road rash.",
    liability_assessment: "Clear Liability - Commercial Defendant",
    liability_reason: "Commercial vehicle cut off bicycle in designated lane. Citation issued.",
    medical_documentation: "Yes - Hospitalization, orthopedic surgery (shoulder plate), collarbone fracture.",
    police_report_status: "Filed",
    police_report: "Yes - Amazon driver cited for failure to yield.",
    insurance_status: "Yes - Amazon Commercial Liability Policy (high coverage).",
    viability_score: "98",
    recommended_action: "Accept Case - Send Retainer",
    case_evaluation_memo: "### CASE EVALUATION MEMO\n\n**Client Name**: Daniel Craig\n**Accident Date**: 6 days ago\n**Liability**: Clear liability. Commercial vehicle cut off bicyclist in dedicated bike lane. Citation issued.\n**Injuries**: Fractured clavicle requiring open reduction internal fixation (ORIF surgery), severe abrasions.\n**Damages**: Substantial medical bills, surgical hardware, permanent scarring potential, lost wages.\n**Recommendation**: Accept case immediately, high value case, commercial policy limits.\n**Action**: Clio Matter created and Retainer signed.",
    extraction_status: "Completed",
    created_at: daysAgo(4.05),
    raw_payload: null
  },
  {
    id: "eval-5",
    call_id: "call-5",
    client_name: "Amanda Seyfried",
    accident_date: daysAgo(10).split("T")[0],
    incident_summary: "Stylist at a hair salon left bleaching chemicals on client's scalp for an excessive duration. Client suffered second-degree chemical burns on her scalp, leading to patch alopecia (permanent hair loss). Dermatologist confirmed diagnosis.",
    liability_assessment: "Strong Professional Liability / Negligence",
    liability_reason: "Negligent chemical application leading to bodily injury.",
    medical_documentation: "Yes - Dermatologist report, second-degree chemical burns, hair loss prognosis.",
    police_report_status: "Not Applicable",
    police_report: "No - Not a police matter.",
    insurance_status: "Pending - Salon refunding service but withholding liability insurance details.",
    viability_score: "80",
    recommended_action: "Accept Case - Send Retainer",
    case_evaluation_memo: "### CASE EVALUATION MEMO\n\n**Client Name**: Amanda Seyfried\n**Accident Date**: 10 days ago\n**Liability**: Strong liability. Chemical application time exceeded salon protocols. Photos show clear burns.\n**Injuries**: Second-degree chemical scalp burns, permanent localized alopecia, significant emotional distress.\n**Recommendation**: Accept case. Send spoliation letter to salon to preserve video, employee records, and chemical logs.",
    extraction_status: "Completed",
    created_at: daysAgo(5.75),
    raw_payload: null
  },
  {
    id: "eval-6",
    call_id: "call-6",
    client_name: "Robert Downey",
    accident_date: daysAgo(8).split("T")[0],
    incident_summary: "Slipped on sidewalk ice outside apartment building. Sidewalk was public. Twisted ankle but did not seek medical treatment. Ankle is currently fine.",
    liability_assessment: "De Minimis Liability & Damages",
    liability_reason: "No medical damages, municipal natural accumulation rules.",
    medical_documentation: "No - No doctor visit, self-treated with ice, recovered.",
    police_report_status: "Not Applicable",
    police_report: "No - No report.",
    insurance_status: "No - Sidewalk is public property; municipal liability is highly restricted.",
    viability_score: "15",
    recommended_action: "Decline Case",
    case_evaluation_memo: "### CASE EVALUATION MEMO\n\n**Client Name**: Robert Downey\n**Accident Date**: 8 days ago\n**Liability**: Very low. Natural accumulation of ice is standard risk. Public sidewalk places liability on city which has sovereign immunity defenses.\n**Injuries**: De minimis. Twisted ankle, recovered, no medical bills.\n**Recommendation**: Decline case. No damages, tough liability.",
    extraction_status: "Completed",
    created_at: daysAgo(7.28),
    raw_payload: null
  }
];

export const MOCK_DOCUSEAL_RETAINERS: DocusealRetainer[] = [
  {
    id: "ret-1",
    call_id: "call-1",
    clio_matter_id: "10928374",
    client_name: "Sarah Jenkins",
    client_email: "sarah.jenkins@example.com",
    template_id: "tmpl_pi_retainer_v2",
    submission_id: "sub-1",
    external_id: "call-1-ret",
    status: "completed",
    sent_at: daysAgo(0.09),
    completed_at: daysAgo(0.08),
    expire_at: daysAgo(-20),
    document_url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    audit_log_url: "https://docuseal.com/audit/sub-1",
    docuseal_response: '{"status":"completed","client":"Sarah Jenkins"}',
    webhook_payload: null,
    created_at: daysAgo(0.09),
    updated_at: daysAgo(0.08)
  },
  {
    id: "ret-2",
    call_id: "call-2",
    clio_matter_id: "10928375",
    client_name: "Marcus Aurelius",
    client_email: "marcus.aurelius@example.com",
    template_id: "tmpl_pi_retainer_v2",
    submission_id: "sub-2",
    external_id: "call-2-ret",
    status: "sent",
    sent_at: daysAgo(1.15),
    completed_at: null,
    expire_at: daysAgo(-25),
    document_url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    audit_log_url: "https://docuseal.com/audit/sub-2",
    docuseal_response: '{"status":"sent"}',
    webhook_payload: null,
    created_at: daysAgo(1.15),
    updated_at: daysAgo(1.15)
  },
  {
    id: "ret-4",
    call_id: "call-4",
    clio_matter_id: "10928378",
    client_name: "Daniel Craig",
    client_email: "daniel.craig@example.com",
    template_id: "tmpl_pi_retainer_v2",
    submission_id: "sub-4",
    external_id: "call-4-ret",
    status: "completed",
    sent_at: daysAgo(4.0),
    completed_at: daysAgo(3.95),
    expire_at: daysAgo(-26),
    document_url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    audit_log_url: "https://docuseal.com/audit/sub-4",
    docuseal_response: '{"status":"completed"}',
    webhook_payload: null,
    created_at: daysAgo(4.0),
    updated_at: daysAgo(3.95)
  },
  {
    id: "ret-5",
    call_id: "call-5",
    clio_matter_id: null,
    client_name: "Amanda Seyfried",
    client_email: "amanda.s@example.com",
    template_id: "tmpl_pi_retainer_v2",
    submission_id: "sub-5",
    external_id: "call-5-ret",
    status: "sent",
    sent_at: daysAgo(5.7),
    completed_at: null,
    expire_at: daysAgo(-28),
    document_url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    audit_log_url: "https://docuseal.com/audit/sub-5",
    docuseal_response: '{"status":"sent"}',
    webhook_payload: null,
    created_at: daysAgo(5.7),
    updated_at: daysAgo(5.7)
  }
];
